name: AntiLaby-1.9
author: Nathan_N
version: 1.1.1
website: https://www.spigotmc.org/members/nathan_n.112032/
main: net.nathann.mc.antilaby.AntiLaby
permission:
  antilaby.*:
    description: antilaby permissions
  antilaby.bypass:
    description: allows you to bypass the protection
    default: OP
commands:
  antilaby:
    usage: /antilaby
    description: information about the plugin