name: AntiLaby
author: Nathan_N
version: 1.3
description: Disable LabyMod functions! Bukkit, Spigot + BungeeCord support
website: https://www.spigotmc.org/resources/21347/
main: com.github.nathannr.antilaby.main.AntiLaby
permission:
  antilaby.*:
    description: Antilaby permissions
  antilaby.bypass:
    description: Allows you to bypass the protection
    default: OP
commands:
  antilaby:
    usage: /antilaby
    description: Information about the plugin